"""GitHub API integration.

`GitHubService` owns GitHub App authentication and read operations such as fetching PR diffs.
`GitHubReviewPublisher` owns writing review summaries and inline comments back to pull requests.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import TYPE_CHECKING, cast

from github import Auth, Github
from github.Commit import Commit
from github.GithubException import GithubException
from github.PullRequest import PullRequest
from github.PullRequest import ReviewComment as GitHubReviewComment
from github.PullRequestComment import PullRequestComment
from github.PullRequestReview import PullRequestReview
from github.Repository import Repository

from app.models.schemas.code_review import (
    CodeReviewResult,
    ReviewSeverity,
)
from app.models.schemas.code_review import (
    ReviewComment as CodeReviewComment,
)

if TYPE_CHECKING:
    from app.core.config import Settings

logger = logging.getLogger(__name__)

BOT_NAME = "Synapse AI Code Review Bot"
BOT_FOOTER = (
    f"---\n"
    f"<sub>🤖 Generated by **{BOT_NAME}** · "
    f"Not a substitute for human review</sub>"
)

SEVERITY_BADGE: dict[ReviewSeverity, str] = {
    ReviewSeverity.LOW: "🟢 Low",
    ReviewSeverity.MEDIUM: "🟡 Medium",
    ReviewSeverity.HIGH: "🔴 High",
}


class GitHubServiceError(Exception):
    """Raised when GitHub API operations fail."""


class GitHubService:
    """GitHub App client for repository and pull request operations."""

    def __init__(self, settings: Settings) -> None:
        self._settings = settings

    def _load_private_key(self) -> str:
        from app.core.github_key import GitHubKeyError, load_github_app_private_key

        try:
            return load_github_app_private_key(self._settings)
        except GitHubKeyError as exc:
            raise GitHubServiceError(str(exc)) from exc

    def get_github_client(self, installation_id: int) -> Github:
        """Return an authenticated PyGithub client for a GitHub App installation."""
        if not self._settings.github_app_id:
            raise GitHubServiceError("GITHUB_APP_ID is not configured.")

        private_key = self._load_private_key()
        app_auth = Auth.AppAuth(self._settings.github_app_id, private_key)
        installation_auth = app_auth.get_installation_auth(installation_id)
        return Github(auth=installation_auth)

    def fetch_pull_request_diff(
        self,
        installation_id: int,
        repository_full_name: str,
        pr_number: int,
    ) -> str:
        """Fetch the raw unified diff for a pull request via the GitHub API."""
        github = self.get_github_client(installation_id)
        try:
            repo: Repository = github.get_repo(repository_full_name)
            pull: PullRequest = repo.get_pull(pr_number)
            status, _, diff_body = repo._requester.requestJson(
                "GET",
                pull.url,
                headers={"Accept": "application/vnd.github.v3.diff"},
            )
        except GithubException as exc:
            raise GitHubServiceError(f"GitHub API error: {exc.data}") from exc

        if status >= 400:
            raise GitHubServiceError(f"Failed to fetch PR diff (HTTP {status}).")

        return diff_body


@dataclass(frozen=True)
class PostedReviewComment:
    """Metadata for a comment successfully posted to GitHub."""

    file_path: str
    line_number: int
    comment_id: int
    html_url: str


def format_review_comment_body(comment: CodeReviewComment) -> str:
    """Render a single inline review comment as GitHub-flavored Markdown."""
    severity_label = SEVERITY_BADGE.get(comment.severity, str(comment.severity.value))
    return (
        f"> 🤖 **{BOT_NAME}**\n"
        f"> **Severity:** {severity_label}\n\n"
        f"### Suggested fix\n\n"
        f"{comment.suggested_fix.strip()}\n\n"
        f"{BOT_FOOTER}"
    )


def format_review_summary_body(result: CodeReviewResult) -> str:
    """Render a PR-level summary comment when the review completes."""
    if not result.comments:
        return (
            f"## ✅ {BOT_NAME}\n\n"
            "No security, performance, or logic issues were identified in the reviewed diff.\n\n"
            f"{BOT_FOOTER}"
        )

    high = sum(1 for c in result.comments if c.severity == ReviewSeverity.HIGH)
    medium = sum(1 for c in result.comments if c.severity == ReviewSeverity.MEDIUM)
    low = sum(1 for c in result.comments if c.severity == ReviewSeverity.LOW)

    parts = [
        f"## 🔍 {BOT_NAME} — Summary\n\n",
        "| Severity | Count |\n",
        "|----------|------:|\n",
        f"| 🔴 High | {high} |\n",
        f"| 🟡 Medium | {medium} |\n",
        f"| 🟢 Low | {low} |\n\n",
        f"**{len(result.comments)}** finding(s); see **Files changed** for inline notes "
        "on exact lines.\n\n",
        "### Findings (quick view)\n\n",
    ]
    for idx, c in enumerate(result.comments, start=1):
        badge = SEVERITY_BADGE.get(c.severity, str(c.severity.value))
        path = c.file_path.lstrip("/")
        preview = " ".join(c.suggested_fix.strip().split())
        if len(preview) > 200:
            preview = preview[:197] + "…"
        parts.append(
            f"{idx}. {badge} · **{c.issue_type}** · `{path}:{c.line_number}`  \n"
            f"   {preview}\n\n"
        )
    parts.append(BOT_FOOTER)
    return "".join(parts)


class GitHubReviewPublisher:
    """Publish structured LLM review results as GitHub pull request comments."""

    def __init__(self, github_service: GitHubService) -> None:
        self._github_service = github_service

    def post_inline_review_comments(
        self,
        *,
        installation_id: int,
        repository_full_name: str,
        pr_number: int,
        head_sha: str,
        review: CodeReviewResult,
    ) -> list[PostedReviewComment]:
        """
        Post a batched pull request review with inline comments.

        Returns metadata for inline comments successfully created by the review.
        Falls back to per-comment posting when GitHub rejects the batch because
        one or more comment locations are not valid for the diff.
        """
        github = self._github_service.get_github_client(installation_id)
        try:
            repo: Repository = github.get_repo(repository_full_name)
            pull: PullRequest = repo.get_pull(pr_number)
            commit = repo.get_commit(head_sha)
        except GithubException as exc:
            raise GitHubServiceError(f"Failed to load pull request: {exc.data}") from exc

        summary_body = format_review_summary_body(review)
        comment_dicts: list[GitHubReviewComment] = [
            GitHubReviewComment(
                path=comment.file_path.lstrip("/"),
                line=comment.line_number,
                body=format_review_comment_body(comment),
                side="RIGHT",
            )
            for comment in review.comments
        ]

        try:
            created_review = pull.create_review(
                commit=commit,
                body=summary_body,
                event="COMMENT",
                comments=comment_dicts,
            )
        except GithubException as exc:
            if exc.status != 422:
                raise GitHubServiceError(f"Failed to post pull request review: {exc.data}") from exc
            posted = self._post_inline_review_comments_individually(
                pull=pull,
                commit=commit,
                comments=review.comments,
            )
        else:
            posted = [
                PostedReviewComment(
                    file_path=gh_comment.path,
                    line_number=gh_comment.line,
                    comment_id=gh_comment.id,
                    html_url=gh_comment.html_url,
                )
                for gh_comment in self._posted_comments_from_review(
                    pull=pull,
                    review=created_review,
                )
            ]

        logger.info(
            "Posted %d/%d inline review comments on %s#%s",
            len(posted),
            len(review.comments),
            repository_full_name,
            pr_number,
        )
        return posted

    def _post_inline_review_comments_individually(
        self,
        *,
        pull: PullRequest,
        commit: Commit,
        comments: list[CodeReviewComment],
    ) -> list[PostedReviewComment]:
        posted: list[PostedReviewComment] = []

        for comment in comments:
            body = format_review_comment_body(comment)
            try:
                gh_comment = pull.create_review_comment(
                    body=body,
                    commit=commit,
                    path=comment.file_path.lstrip("/"),
                    line=comment.line_number,
                )
            except GithubException as exc:
                logger.warning(
                    "Skipped inline comment on %s:%s — %s",
                    comment.file_path,
                    comment.line_number,
                    exc.data,
                )
                continue

            posted.append(
                PostedReviewComment(
                    file_path=comment.file_path,
                    line_number=comment.line_number,
                    comment_id=gh_comment.id,
                    html_url=gh_comment.html_url,
                )
            )

        return posted

    def _posted_comments_from_review(
        self,
        *,
        pull: PullRequest,
        review: PullRequestReview,
    ) -> list[PullRequestComment]:
        review_comments = getattr(review, "comments", None)
        if isinstance(review_comments, list):
            return cast(list[PullRequestComment], review_comments)

        return [
            comment
            for comment in pull.get_review_comments()
            if comment.pull_request_review_id == review.id
        ]
