"""Post AI-generated review comments back to GitHub pull requests."""

from __future__ import annotations

import logging
from dataclasses import dataclass

from github.GithubException import GithubException
from github.PullRequest import PullRequest
from github.Repository import Repository

from app.models.schemas.code_review import CodeReviewResult, ReviewComment, ReviewSeverity
from app.services.github_service import GitHubService, GitHubServiceError

logger = logging.getLogger(__name__)

BOT_NAME = "Synapse AI Code Review Bot"
BOT_FOOTER = (
    f"---\n"
    f"<sub>🤖 Generated by **{BOT_NAME}** · "
    f"Not a substitute for human review</sub>"
)

SEVERITY_BADGE: dict[ReviewSeverity, str] = {
    ReviewSeverity.LOW: "🟢 Low",
    ReviewSeverity.MEDIUM: "🟡 Medium",
    ReviewSeverity.HIGH: "🔴 High",
}


@dataclass(frozen=True)
class PostedReviewComment:
    """Metadata for a comment successfully posted to GitHub."""

    file_path: str
    line_number: int
    comment_id: int
    html_url: str


def format_review_comment_body(comment: ReviewComment) -> str:
    """Render a single inline review comment as GitHub-flavored Markdown."""
    severity_label = SEVERITY_BADGE.get(comment.severity, str(comment.severity.value))
    return (
        f"> 🤖 **{BOT_NAME}**\n"
        f"> **Severity:** {severity_label}\n\n"
        f"### Suggested fix\n\n"
        f"{comment.suggested_fix.strip()}\n\n"
        f"{BOT_FOOTER}"
    )


def format_review_summary_body(result: CodeReviewResult) -> str:
    """Render a PR-level summary comment when the review completes."""
    if not result.comments:
        return (
            f"## ✅ {BOT_NAME}\n\n"
            "No security, performance, or logic issues were identified in the reviewed diff.\n\n"
            f"{BOT_FOOTER}"
        )

    high = sum(1 for c in result.comments if c.severity == ReviewSeverity.HIGH)
    medium = sum(1 for c in result.comments if c.severity == ReviewSeverity.MEDIUM)
    low = sum(1 for c in result.comments if c.severity == ReviewSeverity.LOW)

    parts = [
        f"## 🔍 {BOT_NAME} — Summary\n\n",
        "| Severity | Count |\n",
        "|----------|------:|\n",
        f"| 🔴 High | {high} |\n",
        f"| 🟡 Medium | {medium} |\n",
        f"| 🟢 Low | {low} |\n\n",
        f"**{len(result.comments)}** finding(s); see **Files changed** for inline notes on exact lines.\n\n",
        "### Findings (quick view)\n\n",
    ]
    for idx, c in enumerate(result.comments, start=1):
        badge = SEVERITY_BADGE.get(c.severity, str(c.severity.value))
        path = c.file_path.lstrip("/")
        preview = " ".join(c.suggested_fix.strip().split())
        if len(preview) > 200:
            preview = preview[:197] + "…"
        parts.append(
            f"{idx}. {badge} · **{c.issue_type}** · `{path}:{c.line_number}`  \n"
            f"   {preview}\n\n"
        )
    parts.append(BOT_FOOTER)
    return "".join(parts)


class GitHubReviewPublisher:
    """Publish structured LLM review results as GitHub pull request comments."""

    def __init__(self, github_service: GitHubService) -> None:
        self._github_service = github_service

    def post_inline_review_comments(
        self,
        *,
        installation_id: int,
        repository_full_name: str,
        pr_number: int,
        head_sha: str,
        review: CodeReviewResult,
    ) -> list[PostedReviewComment]:
        """
        Post inline review comments on the pull request diff.

        Also posts a summary comment on the PR conversation thread.
        """
        github = self._github_service.get_github_client(installation_id)
        try:
            repo: Repository = github.get_repo(repository_full_name)
            pull: PullRequest = repo.get_pull(pr_number)
            commit = repo.get_commit(head_sha)
        except GithubException as exc:
            raise GitHubServiceError(f"Failed to load pull request: {exc.data}") from exc

        posted: list[PostedReviewComment] = []

        for comment in review.comments:
            body = format_review_comment_body(comment)
            try:
                gh_comment = pull.create_review_comment(
                    body=body,
                    commit=commit,
                    path=comment.file_path.lstrip("/"),
                    line=comment.line_number,
                )
            except GithubException as exc:
                logger.warning(
                    "Skipped inline comment on %s:%s — %s",
                    comment.file_path,
                    comment.line_number,
                    exc.data,
                )
                continue

            posted.append(
                PostedReviewComment(
                    file_path=comment.file_path,
                    line_number=comment.line_number,
                    comment_id=gh_comment.id,
                    html_url=gh_comment.html_url,
                )
            )

        summary_body = format_review_summary_body(review)
        try:
            pull.create_issue_comment(summary_body)
        except GithubException as exc:
            logger.warning("Failed to post PR summary comment: %s", exc.data)

        logger.info(
            "Posted %d/%d inline review comments on %s#%s",
            len(posted),
            len(review.comments),
            repository_full_name,
            pr_number,
        )
        return posted
